# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3ae7b63077cbed6ec237d519456e37aeb04f43bc20372144c4c15aad69296196ad04d004a5ac6fe0a657bca1bf4292c2ddbcc8462f7884a1fde8d23c25f4db8

test:
  secret_key_base: 5655cfbd6c122e065b9234ce56d9c20e0c6a9e27248ae3f4cb673b0c7b473f2853016041697f9fe4f870b4b9f3a462f63eb8dc2a5cdba07f7a97dc74c24883fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
